name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        API_ID: ${{secrets.KEK}}
        API_HASH: ${{secrets.LEL}}
        TOKEN: ${{secrets.UWU}}
        BOTUSERNAME: ${{secrets.OWO}}
      run: docker build . --file Dockerfile
